In [1]:
import tensorflow as tf
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

[name: "/cpu:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 11059771515100880503]

In [17]:
import sys
import numpy as np
import tensorflow as tf
from datetime import datetime
import time

for SIZE in [1000, 2000]:
    device_name = 'cpu'  # Choose device from cmd line. Options: gpu or cpu
    shape = (SIZE, SIZE*2)
    if device_name == "gpu":
        device_name = "/gpu:0"
    else:
        device_name = "/cpu:0"

    with tf.device(device_name):
        random_matrix = tf.random_normal(shape=shape, stddev=10, mean=1)
        dot_operation = tf.matmul(random_matrix, tf.transpose(random_matrix))
        sum_operation = tf.reduce_sum(dot_operation)
    

    startTime = time.time()
    with tf.Session(config=tf.ConfigProto(allow_soft_placement=True, log_device_placement=True)) as session:
            result = session.run(sum_operation)
            print(result)

    # It can be hard to see the results on the terminal with lots of output -- add some newlines to improve readability.
    print("\n" * 3)
    print("Shape:", shape, "Device:", device_name)
    print("Time taken:", time.time() - startTime)

    print("\n" * 3)

2.21138e+09




('Shape:', (1000, 2000), 'Device:', '/cpu:0')
('Time taken:', 0.3183300495147705)




1.68682e+10




('Shape:', (2000, 4000), 'Device:', '/cpu:0')
('Time taken:', 1.332108974456787)






In [32]:
shape = (10, 1000)
device_names = ['/cpu:0', '/gpu:1']
for device_name in device_names:
    with tf.device(device_name):
        random_matrix = tf.random_normal(stddev=1, mean=0, shape=shape, name='a')
        dot_operation = tf.matmul(random_matrix, tf.transpose(random_matrix))
        sum_operation = tf.reduce_sum(dot_operation)

sess = tf.Session(config=tf.ConfigProto(allow_soft_placement=True, log_device_placement=True))
result = sess.run(sum_operation)
print(result)


10647.3


In [12]:
sum_operation

<tf.Tensor 'Sum_10:0' shape=() dtype=float32>

In [36]:
# Creates a graph.
with tf.device('/cpu:1'):
    a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
    b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
    c = tf.matmul(a, tf.transpose(b))
# Creates a session with log_device_placement set to True.
sess = tf.Session(config=tf.ConfigProto(allow_soft_placement=True, log_device_placement=True))
# Runs the op.
print sess.run(c)

ValueError: Dimensions must be equal, but are 3 and 2 for 'MatMul_52' (op: 'MatMul') with input shapes: [2,3], [2,3].

In [8]:
with tf.device('/gpu:0'):
    a = tf.constant(list(range(10)), shape=[2, 5], name='a')
    b = tf.constant(list(range(10, 20)), shape=[2, 5], name='b')
    c = tf.matmul(a, tf.transpose(b))
sess = tf.Session(config=tf.ConfigProto(allow_soft_placement=True))
print sess.run(a)
print sess.run(b)
print sess.run(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]
[[130 180]
 [430 605]]
